import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

const tournaments = [
  // Central Florida
  {
    name: "US Open Pickleball Championships 2026",
    slug: "us-open-pickleball-championships-2026",
    description: "The most prestigious and vibrant pickleball tournament on the planet. The US Open returns to Naples with world-class competition across all skill levels.",
    date_start: "2026-04-11",
    date_end: "2026-04-18",
    city: "Naples",
    county: "Collier",
    region: "South Florida",
    venue_name: "East Naples Community Park",
    venue_address: "3500 Thomasson Dr, Naples, FL 34112",
    lat: 26.1095,
    lng: -81.7715,
    level: "All Levels",
    categories: ["Pro/Open", "Seniors", "Amateur", "Junior"],
    featured: true,
    registration_url: "https://www.usopenpickleball.com/",
    entry_fee_min: 75,
    entry_fee_max: 150,
    format: "Double Elimination",
    status: "approved",
    tier: "premium",
  },
  {
    name: "Pictona Rookie Rally 2026",
    slug: "pictona-rookie-rally-2026",
    description: "Perfect for newer players! Featuring Adult Division (2.5 & 3.0 skill levels) and Junior Division with Round Robin + Top 4 Playoff Format at Pictona's world-class 49-court facility.",
    date_start: "2026-01-09",
    date_end: "2026-01-11",
    city: "Holly Hill",
    county: "Volusia",
    region: "Central Florida",
    venue_name: "Pictona at Holly Hill",
    venue_address: "1060 US-1, Holly Hill, FL 32117",
    lat: 29.2433,
    lng: -81.0381,
    level: "Amateur",
    categories: ["Amateur", "Junior"],
    featured: true,
    registration_url: "https://pictona.org/pickleball-tournaments-florida/",
    entry_fee_min: 45,
    entry_fee_max: 65,
    format: "Round Robin + Playoffs",
    status: "approved",
    tier: "pro",
  },
  {
    name: "Hillsborough Cupid's Challenge",
    slug: "hillsborough-cupids-challenge-2026",
    description: "Part of Hillsborough County's first-ever Pickleball Tournament Series. Celebrate Valentine's Day on the courts!",
    date_start: "2026-02-14",
    date_end: "2026-02-14",
    city: "Thonotosassa",
    county: "Hillsborough",
    region: "Tampa Bay",
    venue_name: "Branchton Park",
    venue_address: "12001 Pruett Rd, Thonotosassa, FL 33592",
    lat: 28.0614,
    lng: -82.2851,
    level: "All Levels",
    categories: ["Mixed", "Open"],
    featured: false,
    registration_url: "https://hcfl.gov/",
    entry_fee_min: 25,
    entry_fee_max: 40,
    format: "Round Robin",
    status: "approved",
    tier: "free",
  },
  {
    name: "Sebring Pickleball Shootout 2026",
    slug: "sebring-pickleball-shootout-2026",
    description: "Competitive pickleball action in the heart of Florida. Join players from across the state for this exciting shootout event.",
    date_start: "2026-01-10",
    date_end: "2026-01-10",
    city: "Sebring",
    county: "Highlands",
    region: "Central Florida",
    venue_name: "Sebring Recreation Club",
    venue_address: "333 Pomegranate Ave, Sebring, FL 33870",
    lat: 27.4956,
    lng: -81.4409,
    level: "Intermediate",
    categories: ["Open", "Seniors"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 35,
    entry_fee_max: 50,
    format: "Double Elimination",
    status: "approved",
    tier: "free",
  },
  // South Florida
  {
    name: "APP Fort Lauderdale Open 2026",
    slug: "app-fort-lauderdale-open-2026",
    description: "The Association of Pickleball Players brings top-tier competition to The Fort in Fort Lauderdale. Watch the pros and compete in amateur brackets.",
    date_start: "2026-03-25",
    date_end: "2026-03-29",
    city: "Fort Lauderdale",
    county: "Broward",
    region: "South Florida",
    venue_name: "The Fort",
    venue_address: "891 SW 34th St, Fort Lauderdale, FL 33315",
    lat: 26.0901,
    lng: -80.1618,
    level: "All Levels",
    categories: ["Pro/Open", "Amateur", "Seniors"],
    featured: true,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 60,
    entry_fee_max: 125,
    format: "Double Elimination",
    status: "approved",
    tier: "premium",
  },
  {
    name: "FORT Winter Club Championship",
    slug: "fort-winter-club-championship-2026",
    description: "Kick off the new year at The Fort's Winter Club Championship. Great competition and community atmosphere.",
    date_start: "2026-01-24",
    date_end: "2026-01-24",
    city: "Fort Lauderdale",
    county: "Broward",
    region: "South Florida",
    venue_name: "The Fort",
    venue_address: "891 SW 34th St, Fort Lauderdale, FL 33315",
    lat: 26.0901,
    lng: -80.1618,
    level: "Intermediate",
    categories: ["Open", "Mixed"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 40,
    entry_fee_max: 55,
    format: "Round Robin",
    status: "approved",
    tier: "pro",
  },
  {
    name: "Pickle for a Cause Winter Classic",
    slug: "pickle-for-cause-winter-classic-2026",
    description: "Competitive 4.5+ tournament benefiting the Make-a-Wish Foundation. Play hard, give back.",
    date_start: "2026-01-24",
    date_end: "2026-01-24",
    city: "Miami",
    county: "Miami-Dade",
    region: "South Florida",
    venue_name: "Sip and Pickle Miami",
    venue_address: "2020 N Bayshore Dr, Miami, FL 33137",
    lat: 25.7959,
    lng: -80.1867,
    level: "Pro/Open",
    categories: ["Charity", "Open"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 50,
    entry_fee_max: 75,
    format: "Double Elimination",
    status: "approved",
    tier: "pro",
  },
  {
    name: "Rumble in the Jungle 2",
    slug: "rumble-in-the-jungle-2-2026",
    description: "Miami's premier multi-day pickleball event returns! Four days of intense competition across all skill levels.",
    date_start: "2026-01-08",
    date_end: "2026-01-11",
    city: "Miami",
    county: "Miami-Dade",
    region: "South Florida",
    venue_name: "Tropical Park",
    venue_address: "7900 SW 40th St, Miami, FL 33155",
    lat: 25.7296,
    lng: -80.3226,
    level: "All Levels",
    categories: ["Open", "Seniors", "Mixed"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 55,
    entry_fee_max: 85,
    format: "Double Elimination",
    status: "approved",
    tier: "pro",
  },
  {
    name: "Pride Center Pickleball Classic",
    slug: "pride-center-pickleball-classic-2026",
    description: "Inclusive and welcoming tournament hosted by The Pride Center. All skill levels welcome!",
    date_start: "2026-01-17",
    date_end: "2026-01-17",
    city: "Wilton Manors",
    county: "Broward",
    region: "South Florida",
    venue_name: "Hagen Park",
    venue_address: "2020 Wilton Dr, Wilton Manors, FL 33305",
    lat: 26.1598,
    lng: -80.1381,
    level: "All Levels",
    categories: ["Open", "Mixed", "Non-profit"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 30,
    entry_fee_max: 45,
    format: "Round Robin",
    status: "approved",
    tier: "free",
  },
  {
    name: "Coral Springs Paddle Tap Tournament",
    slug: "coral-springs-paddle-tap-2026",
    description: "Two days of exciting pickleball action in Coral Springs. Great for intermediate and advanced players.",
    date_start: "2026-01-10",
    date_end: "2026-01-11",
    city: "Coral Springs",
    county: "Broward",
    region: "South Florida",
    venue_name: "Mullins Park",
    venue_address: "10154 W Atlantic Blvd, Coral Springs, FL 33071",
    lat: 26.2431,
    lng: -80.2594,
    level: "Intermediate",
    categories: ["Open", "Seniors"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/",
    entry_fee_min: 40,
    entry_fee_max: 60,
    format: "Double Elimination",
    status: "approved",
    tier: "free",
  },
  {
    name: "World Pickleball Open - Boca Raton",
    slug: "world-pickleball-open-boca-2026",
    description: "Amateur-only round robin doubles event presented by HSS Orthopedics. Great atmosphere at beautiful Patch Reef Park.",
    date_start: "2026-03-14",
    date_end: "2026-03-15",
    city: "Boca Raton",
    county: "Palm Beach",
    region: "South Florida",
    venue_name: "Patch Reef Park",
    venue_address: "2000 NW 51st St, Boca Raton, FL 33431",
    lat: 26.3915,
    lng: -80.1175,
    level: "Amateur",
    categories: ["Amateur", "Mixed"],
    featured: false,
    registration_url: "https://pickleballtournaments.com/tournaments/world-pickleball-open-presented-by-hss-florida",
    entry_fee_min: 50,
    entry_fee_max: 70,
    format: "Round Robin",
    status: "approved",
    tier: "pro",
  },
]

async function seed() {
  console.log('Seeding tournaments...')

  for (const tournament of tournaments) {
    const { data, error } = await supabase
      .from('tournaments')
      .insert(tournament)
      .select()

    if (error) {
      console.error(`Error inserting ${tournament.name}:`, error.message)
    } else {
      console.log(`✓ Added: ${tournament.name}`)
    }
  }

  console.log('\nSeeding complete!')
}

seed()
